import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Get Skilled Up',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <main className='flex items-center w-full h-screen'>
          <div className='bg-cover bg-auth-pattern bg-center w-1/2 h-screen '>
            fdgfjdgf
          </div>
          <div className='w-1/2 h-screen overflow-y-scroll'>{children}</div>
        </main>
      </body>
    </html>
  );
}
