'use client';

import { usePathname } from 'next/navigation';
import Header from '@/components/Header/page';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Get skilled up',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  console.log(pathname);
  const isAuthPage = pathname === '/auth/login' || pathname === '/auth/signup'; // Add more auth pages if needed

  return (
    <html lang='en'>
      <body>
        {!isAuthPage && <Header />}
        {children}
      </body>
    </html>
  );
}
